In [1]:
import pandas as pd
import os
from random import randint
import random 
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('/Users/danielgarcia-barnett/Desktop/prog_choice_reaction_time/Stimuli/Schedules/1_option/schedule-001.par', index_col=0, keep_default_na=False)

In [4]:
df

Empty DataFrame
Columns: []
Index: [  2.0000    0    1.000   1.0000          NULL ,   3.0000    1    2.000   1.0000          line,   5.0000    0    1.000   1.0000          NULL ,   6.0000    1    2.000   1.0000          line,   8.0000    0    1.100   1.0000          NULL ,   9.1000    1    2.000   1.0000          line,  11.1000    0    1.400   1.0000          NULL ,  12.5000    1    2.000   1.0000          line,  14.5000    0    1.000   1.0000          NULL ,  15.5000    1    2.000   1.0000          line,  17.5000    0    1.500   1.0000          NULL ,  19.0000    1    2.000   1.0000          line,  21.0000    0    1.300   1.0000          NULL ,  22.3000    1    2.000   1.0000          line,  24.3000    0    1.300   1.0000          NULL ,  25.6000    1    2.000   1.0000          line,  27.6000    0    1.000   1.0000          NULL ,  28.6000    1    2.000   1.0000          line,  30.6000    0    1.900   1.0000          NULL ,  32.5000    1    2.000   1.0000          line,  34.5000    0    1.000   1.0000          NULL ,  35.5000    1    2.000   1.0000          line,  37.5000    0    1.000   1.0000          NULL ,  38.5000    1    2.000   1.0000          line,  40.5000    0    2.000   1.0000          NULL ,  42.5000    1    2.000   1.0000          line,  44.5000    0    1.200   1.0000          NULL ,  45.7000    1    2.000   1.0000          line,  47.7000    0    1.500   1.0000          NULL ,  49.2000    1    2.000   1.0000          line,  51.2000    0    1.000   1.0000          NULL ,  52.2000    1    2.000   1.0000          line,  54.2000    0    1.200   1.0000          NULL ,  55.4000    1    2.000   1.0000          line,  57.4000    0    1.000   1.0000          NULL ,  58.4000    1    2.000   1.0000          line,  60.4000    0    1.200   1.0000          NULL ,  61.6000    1    2.000   1.0000          line,  63.6000    0    1.700   1.0000          NULL ,  65.3000    1    2.000   1.0000          line,  67.3000    0    1.100   1.0000          NULL ,  68.4000    1    2.000   1.0000          line,  70.4000    0    1.200   1.0000          NULL ,  71.6000    1    2.000   1.0000          line,  73.6000    0    1.600   1.0000          NULL ,  75.1999    1    2.000   1.0000          line,  77.1999    0    1.100   1.0000          NULL ,  78.2999    1    2.000   1.0000          line,  80.2999    0    1.800   1.0000          NULL ,  82.0999    1    2.000   1.0000          line,  84.0999    0    1.000   1.0000          NULL ,  85.0999    1    2.000   1.0000          line,  87.0999    0    1.100   1.0000          NULL ,  88.1999    1    2.000   1.0000          line,  90.1999    0    1.100   1.0000          NULL ,  91.2999    1    2.000   1.0000          line,  93.2999    0    1.500   1.0000          NULL ,  94.7999    1    2.000   1.0000          line,  96.7999    0    1.100   1.0000          NULL ,  97.8999    1    2.000   1.0000          line,  99.8999    0    1.600   1.0000          NULL , 101.4999    1    2.000   1.0000          line, 103.4999    0    1.000   1.0000          NULL , 104.4999    1    2.000   1.0000          line, 106.4999    0    1.000   1.0000          NULL , 107.4999    1    2.000   1.0000          line, 109.4999    0    1.300   1.0000          NULL , 110.7999    1    2.000   1.0000          line, 112.7999    0    1.700   1.0000          NULL , 114.4999    1    2.000   1.0000          line, 116.4999    0    1.000   1.0000          NULL , 117.4999    1    2.000   1.0000          line, 119.4999    0    1.100   1.0000          NULL , 120.5999    1    2.000   1.0000          line, 122.5999    0    1.300   1.0000          NULL , 123.8999    1    2.000   1.0000          line, 125.8999    0    1.000   1.0000          NULL , 126.8999    1    2.000   1.0000          line, 128.8999    0    1.100   1.0000          NULL ]

[79 rows x 0 columns]

In [35]:
def get_sched(fpath):
    with open(fpath, 'r') as f:
        lines = f.readlines()
        lines = [line.split() for line in lines]
    schedule = pd.DataFrame(lines, columns=['time', 'stim_code', 'duration', '?', 'stim_type'])
    schedule = schedule.apply(pd.to_numeric, errors='ignore')
    return schedule
def save_sched(df, fpath):
    df.to_csv(fpath, sep=' ', header=False, index=False)

In [40]:
fpath = '/Users/danielgarcia-barnett/Desktop/prog_choice_reaction_time/Stimuli/Schedules/4_options/schedule-001.par'
get_sched(fpath)

/var/folders/w0/4d261sg51qjdphncfst0x4fr0000gn/T/ipykernel_71347/1754735922.py:6: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  schedule = schedule.apply(pd.to_numeric, errors='ignore')

     time  stim_code  duration    ? stim_type
0     0.0          0       1.0  1.0      NULL
1     1.0          2       2.0  1.0    square
2     3.0          0       1.0  1.0      NULL
3     4.0          3       2.0  1.0    circle
4     6.0          0       1.9  1.0      NULL
..    ...        ...       ...  ...       ...
76  123.1          0       1.2  1.0      NULL
77  124.3          1       2.0  1.0      line
78  126.3          0       1.1  1.0      NULL
79  127.4          2       2.0  1.0    square
80  129.4          0       1.6  1.0      NULL

[81 rows x 5 columns]

In [39]:
for dirs, fldrs, files in os.walk('/Users/danielgarcia-barnett/Desktop/prog_choice_reaction_time/Stimuli/Schedules'):
    for file in files:
        if file.endswith('.par'):
            fpath = os.path.join(dirs, file)
            df = get_sched(fpath)
            df = pd.concat([df.iloc[41:42], df]).reset_index(drop=True)
            time = [0]+[float(df.loc[0:i, 'duration'].sum()) for i in range(len(df))]
            df['time'] = time[:-1]
            save_sched(df, fpath)

/var/folders/w0/4d261sg51qjdphncfst0x4fr0000gn/T/ipykernel_71347/1754735922.py:6: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  schedule = schedule.apply(pd.to_numeric, errors='ignore')

In [6]:
dirs = '/Users/danielgarcia-barnett/Desktop/prog_choice_reaction_time/Stimuli/Schedules/practice'
stim_list = ['line', 'square', 'circle', 'triangle']*2
for i in range(100):
    random.shuffle(stim_list)
    duration = [np.round(random.uniform(1, 2), 1) for i in range(8)]
    null_data = pd.DataFrame({'duration':duration, 'stim_type':['NULL']*8}).reset_index(drop=True)
    stim_data = pd.DataFrame({'duration':[2]*8, 'stim_type':stim_list}).reset_index(drop=True)
    practice_data = pd.concat([stim_data, null_data], keys=[0,1]).sort_index(level=1).reset_index(drop=True)
    practice_data.to_csv(os.path.join(dirs, f'schedule-{i:03}.csv'))

In [11]:
practice_data

    duration stim_type
0        2.0    square
1        1.8      NULL
2        2.0  triangle
3        1.5      NULL
4        2.0    circle
5        1.8      NULL
6        2.0    circle
7        1.7      NULL
8        2.0    circle
9        1.4      NULL
10       2.0    square
11       1.6      NULL
12       2.0    square
13       1.2      NULL
14       2.0  triangle
15       1.3      NULL
16       2.0  triangle
17       1.1      NULL
18       2.0    circle
19       1.7      NULL
20       2.0      line
21       1.8      NULL
22       2.0      line
23       1.6      NULL
24       2.0    square
25       1.3      NULL
26       2.0  triangle
27       1.4      NULL
28       2.0  triangle
29       1.7      NULL
30       2.0      line
31       1.5      NULL
32       2.0    circle
33       1.4      NULL
34       2.0      line
35       1.5      NULL
36       2.0    square
37       2.0      NULL
38       2.0      line
39       1.1      NULL

In [80]:
df[::-1]

      time  stim_code  duration    ? stim_type
239  419.0          0       1.0  1.0      NULL
238  417.0          1       2.0  1.0      line
237  416.5          0       0.5  1.0      NULL
236  414.5          2       2.0  1.0    square
235  412.5          0       2.0  1.0      NULL
..     ...        ...       ...  ...       ...
4      5.0          4       2.0  1.0    circle
3      4.5          0       0.5  1.0      NULL
2      2.5          1       2.0  1.0      line
1      2.0          0       0.5  1.0      NULL
0      0.0          2       2.0  1.0    square

[240 rows x 5 columns]

# Generating the Order Text Files

In [4]:
order_dirs = '/Users/AP-CNL/Desktop/4RT/Stimuli/Order'

In [8]:
opt_dict = {'1_option':['line'],
            '2_options':['line', 'square'],
            '4_options':['line', 'circle', 'triangle', 'square']}

In [40]:
def get_order(opt_list):
    count = 40 // len(opt_list)
    count_list = [count for i in range(len(opt_list))]
    order_list = []
    i = 40
    while i > 0:
        index = randint(0, len(opt_list)-1)
        if count_list[index] > 0:
            count_list[index] = count_list[index] - 1
            order_list.append(opt_list[index])
            i -= 1
        else:
            continue
    return order_list

In [45]:
for fldr in os.listdir(order_dirs):
    for i in range(1, 101):
        opt_list = get_order(opt_dict[fldr])
        txt_path = os.path.join(order_dirs, fldr, f'order_{i:03}.txt')
        with open(txt_path, 'w') as file:
            file.writelines(f'{opt}/n' for opt in opt_list)

# Other Testing

In [7]:
one_opt_list = os.listdir('/Users/AP-CNL/Desktop/4RT/Stimuli/Order/1_option')
random.shuffle(one_opt_list)
one_opt_list[0]

'order_036.txt'

In [17]:
txt_path = '/Users/AP-CNL/Desktop/4RT/Stimuli/Order/4_options/order_001.txt'
with open(txt_path, 'r') as file:
    order_list = [line.strip() for line in file]

order_list = [item for pair in zip(order_list, ['feedback']*len(order_list)) for item in pair][:-1]
print(order_list)

['circle', 'feedback', 'line', 'feedback', 'triangle', 'feedback', 'square', 'feedback', 'line', 'feedback', 'circle', 'feedback', 'circle', 'feedback', 'square', 'feedback', 'circle', 'feedback', 'line', 'feedback', 'square', 'feedback', 'circle', 'feedback', 'square', 'feedback', 'square', 'feedback', 'line', 'feedback', 'triangle', 'feedback', 'triangle', 'feedback', 'line', 'feedback', 'square', 'feedback', 'triangle', 'feedback', 'line', 'feedback', 'triangle', 'feedback', 'triangle', 'feedback', 'triangle', 'feedback', 'triangle', 'feedback', 'line', 'feedback', 'line', 'feedback', 'square', 'feedback', 'square', 'feedback', 'circle', 'feedback', 'square', 'feedback', 'square', 'feedback', 'triangle', 'feedback', 'line', 'feedback', 'triangle', 'feedback', 'line', 'feedback', 'circle', 'feedback', 'circle', 'feedback', 'circle', 'feedback', 'circle']